# Generated by Django 4.1.2 on 2022-11-08 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('subtitle', models.CharField(max_length=50, verbose_name='subtitle')),
                ('address', models.CharField(max_length=50, verbose_name='government')),
                ('address_detail', models.CharField(max_length=50, verbose_name='cureent_address')),
                ('number_phone', models.CharField(max_length=50, verbose_name='Phone_number')),
                ('working_hours', models.CharField(max_length=50, verbose_name='Working_time')),
                ('waiting_time', models.IntegerField(blank=True, null=True, verbose_name='waiting_time')),
                ('doctor', models.CharField(blank=True, max_length=50, null=True, verbose_name='doctor?')),
                ('who_i', models.TextField(blank=True, max_length=50, null=True, verbose_name='who_i')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='price')),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, verbose_name='facebook')),
                ('twitter', models.CharField(blank=True, max_length=50, null=True, verbose_name='twitter')),
                ('google', models.CharField(blank=True, max_length=50, null=True, verbose_name='google')),
                ('type_of_person', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50, verbose_name='gender')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Persomal_image')),
                ('Specialist_doctor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Specialist_doctor')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
